name: Automate Terraform Deployment
 
on:
  push:
    branches:
      - main
  pull_request:
 
jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
 
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
 
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.6
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
 
    - name: Terraform Init
      run: terraform init
 
    - name: Terraform Plan
      id: plan
      run: terraform plan -out=tfplan
 
    - name: Generate Terraform Docs
      run: |
        chmod +x terraform-docs.sh
        ./terraform-docs.sh
 
    - name: Comment Terraform Docs
      if: github.event_name == 'pull_request'
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        path: terraform-docs.md
 
    - name: Apply Terraform
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve tfplan
